


```{r}
paste_count_helper <- function(x, y){
  return (paste(y, x, "Count", sep = "_"))
}

paste_prop_helper <- function(x, y){
  return (paste(y, x, "Proportion", sep = "_"))
}


per_sample_proportion_summary <- function(x, label="Sigprofiler"){
  tots <- x %>% group_by(Sample) %>%
    summarize(nTotal = sum(Amount)) %>% 
    distinct()
  x <- left_join(x, tots, by = c("Sample"))
  x <- x %>% mutate(Amount = Amount / nTotal)
  x <- x %>% select(-nTotal)
  x <- x %>%
    spread(Signature, Amount)
  mods <- x %>% select(-Sample) %>% names()
  x <- x %>%
    rename_at(mods, paste_prop_helper, label)
  return(x)
}

per_sample_count_summary <- function(x, label="Sigprofiler"){
  
  totalVarName = paste(label, "total", sep="_")
  tots <- x %>% group_by(Sample) %>%
    summarize({{totalVarName}} := sum(Amount)) %>% 
    distinct()
  x <- x %>%
    spread(Signature, Amount)
  mods <- x %>% select(-Sample) %>% names()


  x <- x %>%
    rename_at(mods, paste_count_helper, label)
  x <- left_join(x, tots)
  
  return(x)
}

per_sample_summary <- function(x, label = "tidysig"){
  y <- per_sample_count_summary(x, label)
  z <- per_sample_proportion_summary(x, label)
  ret <- left_join(y, z, by=c("Sample"))
  return(ret)
}

per_sample_summary(id83_proj)
```


```{r}
sv <- read_tsv("~/chernobyl/svs_2020FEB19/REBC_primary_pair_393.SV_consensus_filtered_txt_v3.bp.dedup.tsv")
```

```{r}
r1_plot <- ggplot(sv) + 
  geom_histogram(aes(x = range1)) + 
  theme_minimal_hgrid(14)

r2_plot <- ggplot(sv) + 
  geom_histogram(aes(x = range2)) + 
  theme_minimal_hgrid(14)

save_plot("~/chernobyl/svs_2020FEB19/sv_range_plot.pdf",
          plot_grid(r1_plot, r2_plot, nrow=1,ncol=2),base_width = 12, base_height = 4)

r1_plot <- ggplot(sv) + 
  geom_histogram(aes(x = stdev1)) + 
  theme_minimal_hgrid(14)

r2_plot <- ggplot(sv) + 
  geom_histogram(aes(x = stdev2)) + 
  theme_minimal_hgrid(14)

save_plot("~/chernobyl/svs_2020FEB19/sv_stdev_plot.pdf",
          plot_grid(r1_plot, r2_plot, nrow=1,ncol=2),base_width = 12, base_height = 4)


```


```{r, warning=F, message=F}
maf <- read_tsv("~/chernobyl/analysis/rebc356_overall_sigs/data/rebc356.25feb2020.maf")
```

```{r}
smaf <- maf %>% filter(Variant_Type %in% c("INS", "DEL")) %>%
  select(Tumor_Sample_Barcode, Chromosome,
               Start_position, End_position,
               Variant_Type, Variant_Classification,
               Reference_Allele, Tumor_Seq_Allele1,
               Tumor_Seq_Allele2, ref_context)  %>%
  mutate(Reference_Allele = str_remove(Reference_Allele, "-"),
         Tumor_Seq_Allele2 = str_remove(Tumor_Seq_Allele2, "-")) %>%
  mutate(ref_len = str_length(Reference_Allele),
         alt_len = str_length(Tumor_Seq_Allele2))
```


```{r}
smaf %>% filter(Variant_Type == "DEL" & ref_len == 1 & alt_len == 0) %>% count()
```

