on: [push, pull_request]

name: R-CMD-check

jobs:
    R-CMD-check:
        runs-on: ubuntu-18.04
        container: erictdawson/cowplot
        steps:
            - uses: actions/checkout@v1
            - name: R test
              run: make test
