# This is a basic workflow to help you get started with Actions

name: R-build-test


on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master
    - name: Install dependencies
        run: install.packages(c("remotes", "rcmdcheck", "tidyverse", "cowplot", "usethis", "devtools", "testthat"))
    - name: r-test
        run: cd tests/ && Rscript testthat.R
